coverage:
  precision: 2
  round: down
  range: 95..100

  status:
    project:
      default:
        target: 95%
        threshold: 0.0
        branches: yes
        lines: yes
        functions: yes
        statements: yes

    patch:
      default:
        target: 90%
        threshold: 0.0
        branches: yes
        lines: yes
        functions: yes
        statements: yes

parsers:
  javascript:
    enable_partials: false

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: true

codecov:
  require_ci_to_pass: yes
