#!/usr/bin/env sh

safe_regex="^(feat|((hot|bug)fix)|wip|exp|release|docs|infra|misc)/[\\da-z-]+$"
unsafe_regex="^(main|develop|(staging|release)([/-].*))$"
npx validate-branch-name -r $safe_regex

npx lint-staged
npm run typecheck
