name: Snapshot release

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  REDIS_URL: redis://localhost:6379/0
  NODE_ENV: test
  CI: true

jobs:
  publish:
    name: Prepare and publish to NPM
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:8.0.3-alpine3.21
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:coverage || exit 0

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          verbose: true
          disable_search: true
          files: coverage/cobertura-coverage.xml
          override_commit: ${{ github.sha }}
          flags: ${{ github.sha }}
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          fail_ci_if_error: true
          verbose: true
          disable_search: true
          files: junit.xml
          override_commit: ${{ github.sha }}
          flags: ${{ github.sha }}
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate snapshot version
        run: |
          sha=${{ github.sha }}
          short_sha=$(echo $sha | cut -c1-7)
          timestamp=$(date +%s)
          npm version "0.0.0-$short_sha-$timestamp" --no-git-tag-version

      - name: Bundle the package
        run: npm run typecheck && npm run bundle

      - name: Publish snapshot package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "@ikrbasak:registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
          npm publish --provenance --access public --tag snapshot
